# Generated by Django 5.2.1 on 2025-07-03 16:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('normal', 'Normal')], max_length=30)),
                ('concerns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('acne', 'Acne'), ('redness', 'Redness'), ('dark-spots', 'Dark Spots'), ('aging', 'Aging'), ('dullness', 'Dullness')], max_length=30), blank=True, default=list, size=None)),
                ('preferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('vegan', 'Vegan'), ('fragrance-free', 'Fragrance-Free'), ('cruelty-free', 'Cruelty-Free'), ('alcohol-free', 'Alcohol-Free'), ('non-comedogenic', 'Non-Comedogenic')], max_length=30), blank=True, default=list, size=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('budget_range_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('budget_range_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
