# Generated by Django 5.2.4 on 2025-07-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0004_remove_quizresults_budget_range_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresults',
            name='age_group',
            field=models.CharField(choices=[('under_20', 'Under 20 years old'), ('20_30', '20 to 30 years'), ('30_40', '30 to 40 years'), ('over_40', 'Over 40 years old')], default='20_30', max_length=50),
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='budget',
            field=models.CharField(choices=[('low', 'Under 5$'), ('medium', '5$ to 15$'), ('high', '15$ to 25$'), ('premium', 'Over 25$')], default='5$ to 15$', max_length=50),
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='lifestyle',
            field=models.CharField(choices=[('minimal', 'Short time (maximum 3 steps)'), ('full', 'Desire for a complete routine (+5 steps)'), ('hydration', 'Focus on water supply'), ('anti_aging', 'Focus on anti-aging')], default='Short time (maximum 3 steps)', max_length=50),
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='skin_type',
            field=models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('normal', 'Normal')], max_length=50),
        ),
    ]
