# Generated by Django 5.2.4 on 2025-07-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0005_alter_quizresults_age_group_alter_quizresults_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresults',
            name='age_group',
            field=models.CharField(choices=[('under_20', 'Under 20 years old'), ('20_30', '20 to 30 years'), ('30_40', '30 to 40 years'), ('over_40', 'Over 40 years old')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='budget',
            field=models.CharField(choices=[('low', 'Under 5$'), ('medium', '5$ to 15$'), ('high', '15$ to 25$'), ('premium', 'Over 25$')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='lifestyle',
            field=models.CharField(choices=[('minimal', 'Short time (maximum 3 steps)'), ('full', 'Desire for a complete routine (+5 steps)'), ('hydration', 'Focus on water supply'), ('anti_aging', 'Focus on anti-aging')], max_length=50, null=True),
        ),
    ]
