# Generated by Django 5.2.4 on 2025-07-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0006_alter_quizresults_age_group_alter_quizresults_budget_and_more'),
        ('Quizzes', '0007_set_default_values'),
    ]

    operations = [
    ]
