# Generated by Django 4.2.23 on 2025-08-01 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0008_merge_20250726_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='budget',
        ),
        migrations.AddField(
            model_name='quizresults',
            name='budget_range_max',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quizresults',
            name='budget_range_min',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text Answer'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('slider', 'Slider Scale')], default='single_choice', max_length=255),
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='age_group',
            field=models.CharField(choices=[('under_20', 'Under 20 years old'), ('20_30', '20 to 30 years'), ('30_40', '30 to 40 years'), ('over_40', 'Over 40 years old')], default='20_30', max_length=50),
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='lifestyle',
            field=models.CharField(choices=[('minimal', 'Short time (maximum 3 steps)'), ('full', 'Desire for a complete routine (+5 steps)'), ('hydration', 'Focus on water supply'), ('anti_aging', 'Focus on anti-aging')], default='minimal', max_length=50),
        ),
    ]
