# Generated by Django 4.2.23 on 2025-09-09 13:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0009_alter_question_options_remove_quizresults_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresults',
            old_name='age_group',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='budget_range_max',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='budget_range_min',
        ),
        migrations.AddField(
            model_name='quizresults',
            name='budget',
            field=models.CharField(choices=[('low', 'Under 25$'), ('medium', '25$ to 100$'), ('high', '100$ to 500$'), ('premium', 'Over 500$')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='quizresults',
            name='dryness',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresults',
            name='eye_concern',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('vegan', 'Vegan'), ('fragrance-free', 'Fragrance-Free'), ('cruelty-free', 'Cruelty-Free'), ('alcohol-free', 'Alcohol-Free'), ('non-comedogenic', 'Non-Comedogenic')], max_length=30), blank=True, default=list, size=None),
        ),
    ]
