# Generated by Django 4.2.23 on 2025-08-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0009_alter_question_options_remove_quizresults_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='select_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
