# Generated by Django 4.2.23 on 2025-09-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0010_rename_age_group_quizresults_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresults',
            name='eye_concern',
            field=models.CharField(choices=[('dark_circles', 'Dark Circles'), ('fine_lines_and_wrinkles', 'Fine Lines & Wrinkles'), ('puffiness', 'Puffiness'), ('no_eye_concern', 'No Eye Concern')], max_length=30),
        ),
    ]
