# Generated by Django 5.2.4 on 2025-08-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0010_remove_question_question_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_length',
        ),
    ]
