# Generated by Django 4.2.23 on 2025-08-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0010_remove_question_question_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='select_limit',
        ),
    ]
