# Generated by Django 5.2.4 on 2025-08-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0010_alter_question_question_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_length',
            field=models.CharField(choices=[('short', 'Short'), ('long', 'Long')], default='short', max_length=255),
        ),
    ]
