# Generated by Django 4.2.23 on 2025-08-01 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0011_remove_product_views_alter_product_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutinePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('full', 'Full Plan'), ('hydration', 'Hydration'), ('minimalist', 'Minimalist')], max_length=255)),
                ('steps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.product')),
                ('routine_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_steps', to='Routines.routineplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
