# Generated by Django 4.2.23 on 2025-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinestep',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
