# Generated by Django 5.2.4 on 2025-07-24 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_remove_product_views_alter_product_ratings'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineplan',
            name='name',
            field=models.CharField(choices=[('full', 'Full Plan'), ('hydration', 'Hydration Plan'), ('minimalist', 'Minimalist Plan')], max_length=255),
        ),
        migrations.CreateModel(
            name='RoutineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.product')),
                ('routine_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_steps', to='routines.routineplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
