# Generated by Django 5.2.1 on 2025-07-03 16:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.FloatField()),
                ('category', models.CharField(choices=[('cleanser', 'Cleanser'), ('serum', 'Serum'), ('moisturizer', 'Moisturizer'), ('toner', 'Toner'), ('sunscreen', 'Sunscreen')], max_length=30)),
                ('compatible_skin_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('normal', 'Normal')], max_length=30), blank=True, default=list, size=None)),
                ('concerns_targeted', models.CharField(choices=[('acne', 'Acne'), ('redness', 'Redness'), ('dark-spots', 'Dark Spots'), ('aging', 'Aging'), ('dullness', 'Dullness')], max_length=30)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('niacinamide', 'Niacinamide'), ('hyaluronic_acid', 'Hyaluronic Acid'), ('salicylic_acid', 'Salicylic Acid'), ('retinol', 'Retinol'), ('vitamin_c', 'Vitamin C'), ('ceramides', 'Ceramides'), ('glycolic_acid', 'Glycolic Acid'), ('zinc_oxide', 'Zinc Oxide'), ('tea_tree_oil', 'Tea Tree Oil'), ('aloe_vera', 'Aloe Vera')], max_length=30), blank=True, default=list, size=None)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
            ],
        ),
    ]
