# Generated by Django 5.2.4 on 2025-07-03 18:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_rating_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='concerns_targeted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('acne', 'Acne'), ('redness', 'Redness'), ('dark-spots', 'Dark Spots'), ('aging', 'Aging'), ('dullness', 'Dullness')], max_length=30), blank=True, default=list, size=None),
        ),
    ]
