# Generated by Django 5.2.4 on 2025-07-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
