# Generated by Django 5.2.4 on 2025-08-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_remove_product_views_alter_product_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
