# Generated by Django 4.2.23 on 2025-09-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_remove_product_views_alter_product_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
