# Generated by Django 4.2.23 on 2025-09-10 16:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_product_rating_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='concerns_targeted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('acne_prone', 'Acne-Prone'), ('redness', 'Redness'), ('dark-spots', 'Dark Spots'), ('aging', 'Early Signs of Aging'), ('dullness', 'Dullness'), ('hyperpigmentation', 'Hyperpigmentation'), ('oily_or_blackheads', 'Oily/Blackheads'), ('dryness', 'Dryness & Dehydration'), ('mature_skin', 'Mature Skin'), ('sensitive', 'Sensitive / Rosacea-prone')], max_length=30), blank=True, default=list, size=None),
        ),
    ]
