# Generated by Django 5.2.4 on 2025-07-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsing_history',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('wishlist', 'Wishlist'), ('cart', 'Cart')], max_length=10),
        ),
    ]
